# Generated by Django 5.1.7 on 2025-03-12 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario_aula', models.CharField(choices=[('7:00h', '7:45h'), ('7:45h', '8:30h'), ('8:30h', '9:15h'), ('9:15h', '10:00h'), ('10:00h', '10:45h'), ('10:45h', '11:30h'), ('11:30h', '12:15h'), ('12:15h', '13:00h'), ('13:00h', '13:45h'), ('13:45h', '14:30h'), ('14:30h', '15:15h'), ('15:15h', '16:00h'), ('16:00h', '16:45h'), ('16:45h', '17:30h'), ('17:30h', '18:15h')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie_turma', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Turma_Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materia', models.CharField(choices=[('Matematica', 'Matemática'), ('Portugues', 'Português'), ('Historia', 'História'), ('Geografia', 'Geografia'), ('Quimica', 'Química'), ('Fisica', 'Física'), ('Biologia', 'Biologia')], max_length=50)),
                ('horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.horario')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.professor')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.turma')),
            ],
        ),
    ]
