# Generated by Django 5.1.7 on 2025-03-14 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_dias_semanas_materia_aluno_dias_semanas_aulas_aulas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dias_semanas',
            name='dia',
            field=models.CharField(choices=[('SEG', 'Segunda-Feira'), ('TER', 'Terça-Feira'), ('QUA', 'Quarta-Feira'), ('QUI', 'Quinta-Feira'), ('SEX', 'Sexta-Feira')], max_length=55, unique=True),
        ),
        migrations.AlterField(
            model_name='horario',
            name='horario_aula',
            field=models.CharField(choices=[('7:00h', '7:00h'), ('7:45h', '7:45h'), ('8:30h', '8:30h'), ('9:15h', '9:15h'), ('10:00h', '10:00h'), ('10:45h', '10:45h'), ('11:30h', '11:30h'), ('12:15h', '12:15h'), ('13:00h', '13:00h'), ('13:45h', '13:45h'), ('14:30h', '14:30h'), ('15:15h', '15:15h'), ('16:00h', '16:00h'), ('16:45h', '16:45h'), ('17:30h', '17:30h')], max_length=50, unique=True),
        ),
    ]
