# Generated by Django 5.1.7 on 2025-03-17 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_dias_semanas_dia_alter_horario_horario_aula'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='email',
            field=models.CharField(default='', max_length=255),
        ),
    ]
