# Generated by Django 5.1.1 on 2025-03-18 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_aluno_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='serie_turma',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
