# Generated by Django 5.1.7 on 2025-03-19 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_aluno_options_alter_aluno_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='pk_turma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.turma'),
        ),
    ]
