# Generated by Django 5.1.7 on 2025-03-31 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_aluno_pk_turma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='ra',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
