# Generated by Django 5.1.7 on 2025-03-31 23:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_aluno_ra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='pk_turma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.turma'),
        ),
    ]
